// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }

// src/app/layout.tsx

// src/app/layout.tsx
// import "./globals.css";
// import type { ReactNode } from "react";
// import Link from "next/link";

// export const metadata = {
//   title: "Admin Blog",
//   description: "Admin dashboard for blog (Laravel backend)",
// };

// export default function RootLayout({ children }: { children: ReactNode }) {
//   return (
//     <html lang="en">
//       <body className="min-h-screen bg-slate-50">
//         <div className="flex min-h-screen">
//           {/* Sidebar */}
//           <aside className="w-64 bg-slate-900 text-slate-100 flex flex-col">
//             <div className="px-4 py-4 text-xl font-semibold border-b border-slate-700">
//               Admin Blog
//             </div>
//             <nav className="flex-1 px-4 py-4 space-y-2">
//               <Link
//                 href="/"
//                 className="block px-3 py-2 rounded hover:bg-slate-800"
//               >
//                 Dashboard
//               </Link>
//               <Link
//                 href="/posts"
//                 className="block px-3 py-2 rounded hover:bg-slate-800"
//               >
//                 Posts
//               </Link>
//             </nav>
//           </aside>

//           {/* Main content */}
//           <main className="flex-1 p-6">{children}</main>
//         </div>
//       </body>
//     </html>
//   );
// }

// src/app/layout.tsx

// app/layout.tsx (or app/(site)/layout.tsx)
import "./globals.css";
import type { ReactNode } from "react";
import { poppins } from "./fonts";
import SiteHeader from "./components/SiteHeader";
import "reactjs-tiptap-editor/style.css";

export const metadata = {
  title: "Touript Blog",
  description: "Unfold the Fable – stories from Touript",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en" className={poppins.variable}>
      <body className="bg-white text-slate-900 antialiased font-sans">
        <div className="min-h-screen  text-white">
          <SiteHeader />
          <main className="mx-auto bg-white pt-22 lg:px-0">{children}</main>
        </div>
      </body>
    </html>
  );
}
